call adicionaIndexing('tbl_pessoas', 'idx_pessoa_id_antigo_cliente', 'pes_cliente, pes_id_antigo', 0, 0);
call adicionaIndexing('tbl_financeiro', 'idx_fin_lcto_id_pessoa_antigo', 'mov_receber, lcto_id_pessoa_antigo, lcto_id_antigo', 0, 0);
UPDATE tbl_financeiro SET lcto_id_pessoa = (SELECT pes_id FROM tbl_pessoas WHERE pes_cliente = 1 AND pes_id_antigo = lcto_id_pessoa_antigo) WHERE lcto_id_antigo > 0 AND lcto_id_pessoa_antigo > 0 AND mov_receber = 1;
UPDATE tbl_produtos a LEFT JOIN tbl_grupos b ON (b.gru_id_antigo=a.pro_id_grupo_antigo) SET a.pro_id_grupo=b.gru_id WHERE a.pro_id_grupo_antigo> 0 AND b.gru_id> 0;
-- UPDATE tbl_produtos a LEFT JOIN tbl_pessoas b ON (b.pes_id_antigo=a.pro_id_fornecedor) SET a.pro_id_fornecedor=b.pes_id WHERE a.pro_id_fornecedor> 0 AND b.pes_id> 0;
-- UPDATE tbl_financeiro a LEFT JOIN tbl_pessoas b ON (b.pes_id_antigo = a.lcto_id_pessoa AND b.pes_transportador = 0) SET a.lcto_id_pessoa = b.pes_id WHERE b.pes_id > 0;
-- UPDATE tbl_financeiro SET lcto_id_firma = 1 WHERE lcto_id > 0;
-- UPDATE tbl_financeiro SET lcto_id_pessoa = (SELECT pes_id from tbl_pessoas WHERE pes_id_antigo > 0 AND pes_cliente = 1 AND pes_id_antigo = lcto_id_pessoa) WHERE lcto_id_antigo > 0 AND mov_receber = 1;
-- UPDATE tbl_financeiro SET lcto_id_pessoa = (SELECT pes_id from tbl_pessoas WHERE pes_id_antigo > 0 AND pes_fornecedor = 1 AND pes_id_antigo = lcto_id_pessoa) WHERE lcto_id_antigo > 0 AND mov_pagar = 1;
-- UPDATE tbl_produtos as a LEFT JOIN tbl_pessoas as b ON(a.pro_id_fornecedor = b.pes_id_antigo) SET a.pro_id_fornecedor = b.pes_id WHERE a.pro_id_fornecedor > 0;
UPDATE tbl_financeiro SET lcto_id_pessoa = (SELECT pes_id FROM tbl_pessoas WHERE pes_cliente = 1 AND pes_id_antigo = lcto_id_pessoa_antigo) WHERE lcto_id_pessoa_antigo > 0 AND mov_receber = 1;
UPDATE tbl_financeiro SET lcto_id_pessoa = (SELECT pes_id FROM tbl_pessoas WHERE pes_fornecedor = 1 AND pes_id_antigo = lcto_id_pessoa_antigo) WHERE lcto_id_pessoa_antigo > 0 AND mov_pagar = 1;
update tbl_financeiro SET lcto_valor = 0 WHERE lcto_valor IS NULL;
update tbl_financeiro SET lcto_valor_pago = 0 WHERE lcto_valor_pago IS NULL;  
update tbl_pessoas p set p.pes_pessoa = case when length(replace(replace(replace(replace(p.pes_cnpj_cpf, '/', ''), '-', ''), '.', ''), ' ', '')) >= 14 then 1 else 0 end where pes_id_antigo is not null;
update tbl_pessoas set pes_cod_ibge = (select max(cid_codigo) from tbl_cidades where cid_nome = pes_reside_cidade and cid_uf = pes_reside_uf);
update tbl_produtos set pro_id_tipo_fracionado = case when pro_unidade1 = 'KG' then 0 else 1 end where pro_pesavel = 1;
update tbl_pessoas set pes_fantasia = pes_razaosocial where length(ifnull(pes_fantasia, '')) <= 1;
update tbl_produtos set pro_id_grupo = -1 where pro_id_grupo is null;
update tbl_financeiro set lcto_emissao = lcto_vencimento where lcto_emissao is null;
update tbl_financeiro set lcto_situacao = 1 where lcto_valor = lcto_valor_pago;